development:
  adapter: mysql2
  database: jsprinting_mdo
  username: root
  password:

test:
  adapter: mysql2
  database: jsprinting_mdo
  username: root
  password:

production:
  adapter: mysql2
  database: jsprinting_mdo
  username: root
  password:
